# Generated by Django 4.2 on 2023-05-06 07:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Calculation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("a", models.IntegerField()),
                ("b", models.IntegerField()),
                ("op", models.CharField(max_length=4)),
            ],
        ),
    ]
