# Generated by Django 4.2 on 2023-05-06 08:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("arythmetic", "0002_calculation_result"),
    ]

    operations = [
        migrations.AddField(
            model_name="calculation",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
