# Generated by Django 4.2 on 2023-05-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arythmetic", "0003_calculation_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calculation",
            name="op",
            field=models.CharField(
                choices=[
                    ("add", "add"),
                    ("sub", "sub"),
                    ("mul", "mul"),
                    ("div", "div"),
                ],
                max_length=4,
            ),
        ),
    ]
