# Generated by Django 4.2 on 2023-05-06 08:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arythmetic", "0004_alter_calculation_op"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calculation",
            name="op",
            field=models.CharField(
                choices=[
                    ("add", "add"),
                    ("sub", "sub"),
                    ("mul", "mul"),
                    ("div", "div"),
                ],
                max_length=4,
                validators=[django.core.validators.MinLengthValidator(3)],
            ),
        ),
    ]
