# Generated by Django 4.2 on 2023-06-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rok", models.IntegerField()),
                ("miesiac", models.IntegerField()),
                ("wartosc", models.FloatField()),
                ("data_importu", models.DateTimeField()),
            ],
        ),
    ]
