# Generated by Django 4.2 on 2023-06-04 08:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0002_alter_book_cover_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="category",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
